"""Shared constants used across the package."""

DEFAULT_NAMESPACE = "default"
DEFAULT_CACHE_NAME = "kmcache"
DEFAULT_TTL = 300
DEFAULT_NULL_TTL = 30
DEFAULT_TTL_JITTER = 30
DEFAULT_LOCAL_MAX_SIZE = 10_000
DEFAULT_REDIS_TIMEOUT = 5.0
DEFAULT_BROADCAST_CHANNEL = "kmcache:events"
DEFAULT_CIRCUIT_FAILURE_THRESHOLD = 5
DEFAULT_CIRCUIT_RECOVERY_TIMEOUT = 30.0
DEFAULT_CIRCUIT_HALF_OPEN_MAX_CALLS = 1
